//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Damacanawithdb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int id { get; set; }
        public string name { get; set; }
        public string price { get; set; }
        public Nullable<int> cardId { get; set; }
        public Nullable<int> purchaseId { get; set; }
        public Nullable<int> number { get; set; }
    
        public virtual cart cart { get; set; }
        public virtual purchase purchase { get; set; }
    }
}
